// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginalquilerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginalquiler() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1440, 802));
    driver.findElement(By.linkText("Registro")).click();
    driver.findElement(By.id("Nombre")).click();
    driver.findElement(By.id("Nombre")).sendKeys("Laura");
    driver.findElement(By.id("apellido1")).sendKeys("Gomez");
    driver.findElement(By.id("apellido2")).sendKeys("Prieto");
    driver.findElement(By.id("dni")).sendKeys("56571231F");
    driver.findElement(By.id("email")).sendKeys("lauragp@gmail.com");
    driver.findElement(By.id("location")).sendKeys("Soria");
    driver.findElement(By.id("password")).sendKeys("asdewq");
    driver.findElement(By.id("movil")).click();
    driver.findElement(By.id("movil")).sendKeys("+34621450088");
    driver.findElement(By.id("charge_info")).click();
    driver.findElement(By.id("charge_info")).sendKeys("ES02431298670007");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Iniciar Sesión")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lauragp@gmail.com");
    driver.findElement(By.id("password")).sendKeys("asdewq");
    driver.findElement(By.name("loginBtn")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.id("category-dropdown")).click();
    {
      WebElement dropdown = driver.findElement(By.id("category-dropdown"));
      dropdown.findElement(By.xpath("//option[. = 'De Construcción']")).click();
    }
    driver.findElement(By.cssSelector("#category button")).click();
    driver.findElement(By.cssSelector(".col:nth-child(1) .text-center:nth-child(1) > .btn")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".d-flex > .btn-outline-dark")).click();
    driver.findElement(By.linkText("Alquilar herramientas")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
