// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PublicarbuscarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void publicarbuscar() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1200, 758));
    driver.findElement(By.linkText("Iniciar Sesión")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lauragp@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("asdewq");
    driver.findElement(By.name("loginBtn")).click();
    driver.findElement(By.linkText("Publicar Anuncio")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Cortacesped");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Corta-cesped");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Corta-césped");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("El cortacésped eléctrico ARM 32 de Bosch resulta excelente para el mantenimiento de pequeñas superficies de césped de hasta 150 m².");
    driver.findElement(By.id("price")).click();
    driver.findElement(By.id("price")).sendKeys("35.98");
    driver.findElement(By.id("photo")).click();
    driver.findElement(By.id("photo")).sendKeys("C:\\fakepath\\corta cesped.jpeg");
    driver.findElement(By.id("dropdownMenuButton")).click();
    driver.findElement(By.linkText("De Jardinería")).click();
    driver.findElement(By.id("location")).click();
    driver.findElement(By.id("location")).sendKeys("Soria");
    driver.findElement(By.id("charge_info")).click();
    driver.findElement(By.id("charge_info")).sendKeys("ES8000816797982133475859");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("Corta");
    driver.findElement(By.name("title")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.id("location-dropdown")).click();
    {
      WebElement dropdown = driver.findElement(By.id("location-dropdown"));
      dropdown.findElement(By.xpath("//option[. = 'Soria']")).click();
    }
    driver.findElement(By.cssSelector("#location button")).click();
  }
}
